
# Efinity Option Register
# Version: 2025.2.288.2.10
# Date: 2026-04-05 12:45

# Copyright (C) 2013 - 2025 Efinix Inc. All rights reserved.

enable_remote_update=off
seu_wait_interval=0xffffff
enable_seu_crc_check=off
seu_mode=automatic
